# Generated by Django 5.2.7 on 2025-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='GHProblogs/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='images',
            field=models.ManyToManyField(related_name='GHProportfolioimages', to='cms.portfolioimages'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='GHProthumbnails/'),
        ),
    ]
