# Generated by Django 5.2.7 on 2025-11-26 14:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_blog_title_alter_portfolio_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='portfolio_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_picture'),
        ),
    ]
