# Generated by Django 5.2.7 on 2025-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_blog_featured_image_alter_portfolio_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='', max_length=50, null=True),
        ),
    ]
