# Generated by Django 5.2.7 on 2025-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('FURNITURE', 'FURNITURE'), ('ELECTRONICS', 'ELECTRONICS')], default='', max_length=50, null=True),
        ),
    ]
