# Generated by Django 5.2.7 on 2025-12-04 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(verbose_name=1000)),
                ('answer', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaIntro', models.TextField(max_length=2000)),
                ('metaDescription', models.TextField(max_length=5000)),
                ('ordersCompleted', models.PositiveIntegerField(default=0)),
                ('suppliers', models.PositiveIntegerField(default=0)),
                ('experience', models.SmallIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=55)),
                ('office', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name=1000)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
