# Generated by Django 5.2.7 on 2025-12-22 02:09

import cloudinary.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Catalogs_image')),
                ('min_quantity', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('OFFICE_AND_STATIONERY', 'Office and Stationery'), ('IT_AND_ELECTRONICS', 'IT and Electronics'), ('INDUSTRIAL_AND_MANUFACTURING', 'Industrial and Manufacturing'), ('CONSTRUCTION_AND_BUILDING_MATERIALS', 'Construction and Building Materials'), ('ELECTRICAL_AND_POWER', 'Electrical and Power'), ('FURNITURE', 'Furniture'), ('MEDICAL_AND_LABORATORY', 'Medical and Laboratory'), ('FOOD_AND_CONSUMABLES', 'Food and Consumables')], default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
