# Generated by Django 5.2.7 on 2026-01-03 00:08

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_catalog_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('item', models.TextField(max_length=5000)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='rfq_Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioImages',
        ),
    ]
