# Generated by Django 5.2.7 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_rfq_delete_portfolio_delete_portfolioimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='phone',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
