# Generated by Django 5.2.7 on 2026-10-09 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_rfq_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('outreach', 'Outreach / general'), ('rfq_reply', 'Reply to a quote request')], default='outreach', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('reference_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_number', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('valid_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attachments_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reference_year', 'reference_number'), name='unique_reference_per_year')],
            },
        ),
    ]
