# Generated by Django 5.2.7 on 2026-10-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='attachments_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
