# Generated by Django 5.2.7 on 2026-10-09 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_mfadevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to=settings.AUTH_USER_MODEL),
        ),
    ]
