# Generated by Django 5.2.7 on 2026-10-09 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_protect_rfq_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.CharField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('text_body', models.TextField(blank=True)),
                ('attachments_info', models.JSONField(blank=True, default=list)),
                ('spam_score', models.FloatField(blank=True, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='cms_inboxme_receive_283c13_idx'), models.Index(fields=['is_read'], name='cms_inboxme_is_read_fe6e30_idx')],
            },
        ),
    ]
