# Generated by Django 5.2.7 on 2026-10-09 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_inboxmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('sign_in', 'Signed in'), ('sign_in_failed', 'Failed sign-in'), ('password_changed', 'Changed password'), ('two_step_on', 'Turned two-step on'), ('two_step_off', 'Turned two-step off'), ('recovery_codes', 'Made new recovery codes'), ('created', 'Created'), ('updated', 'Edited'), ('deleted', 'Deleted'), ('email_sent', 'Sent an email'), ('quote_received', 'Quote request received')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='cms_auditlo_created_1257e3_idx'), models.Index(fields=['action'], name='cms_auditlo_action_c7cb76_idx')],
            },
        ),
    ]
