# Generated by Django 5.2.7 on 2026-10-09 16:49

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('received', 'Request received'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('sourcing', 'Sourcing'), ('quality', 'Quality check'), ('shipped', 'Shipped'), ('customs', 'Customs'), ('delivered', 'Delivered')], max_length=12)),
                ('headline', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rfq',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rfq',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rfq',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reference_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reference_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('received', 'Request received'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('sourcing', 'Sourcing'), ('quality', 'Quality check'), ('shipped', 'Shipped'), ('customs', 'Customs'), ('delivered', 'Delivered')], default='received', max_length=12),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rfq_Image'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.UniqueConstraint(fields=('reference_year', 'reference_number'), name='unique_rfq_reference_per_year'),
        ),
        migrations.AddField(
            model_name='rfqupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqupdate',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cms.rfq'),
        ),
        migrations.AddIndex(
            model_name='rfqupdate',
            index=models.Index(fields=['rfq', '-created_at'], name='cms_rfqupda_rfq_id_115ad5_idx'),
        ),
    ]
