# Generated by Django 5.2.7 on 2026-10-09 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=40)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('next_try_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.CharField(blank=True, max_length=7)),
                ('attempts_this_month', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
