# Generated by Django 5.2.7 on 2026-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_socialfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='currency',
            field=models.CharField(choices=[('USD', 'US dollar ($)'), ('NGN', 'Nigerian naira (₦)'), ('GBP', 'British pound (£)'), ('EUR', 'Euro (€)'), ('CNY', 'Chinese yuan (¥)'), ('GHS', 'Ghanaian cedi (GH₵)'), ('ZAR', 'South African rand (R)'), ('AED', 'UAE dirham (AED)')], default='USD', max_length=3),
        ),
    ]
