# Generated by Django 5.2.7 on 2026-10-09 19:22

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_metadata_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='experience_year',
            field=models.PositiveSmallIntegerField(default=cms.models.current_year, editable=False),
        ),
    ]
